version: '3.1'

networks:
  main:

services:
  oni-express:
    build: .
    ports:
      - "8080:8080"
    expose:
      - "80"
    networks:
      - main
    volumes:
      - "../ocfl-cm/ocfl:/etc/share/ocfl"

  solr:
    image: solr
    ports:
      - "8983:8983"
    expose:
      - "8983"
    networks:
      - main
    volumes:
      - "./test_solr/:/opt/solr/server/solr/public_ocfl"
    command: solr-precreate public_ocfl

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    expose:
      - "11211"
    networks:
      - main
    

