version: '3.1'

networks:
  main:

services:
  oni-express:
    build: .
    ports:
      - "8080:8080"
    expose:
      - "80"
    networks:
      - main
    volumes:
      - "../oni-indexer/working/:/etc/share/ocfl"

  solr:
    image: solr
    ports:
      - "8983:8983"
    expose:
      - "8983"
    networks:
      - main
    volumes:
      - "./test_solr/:/opt/solr/server/solr/grants"
    command: solr-precreate grants
    logging:
      driver: none

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    expose:
      - "11211"
    networks:
      - main
    logging:
      driver: none
    

