version: '3.1'

networks:
  main:

services:
  oni-express:
    environment:
      - NODE_ENV=development
    build: .
    ports:
      - "8080:8080"
    expose:
      - "80"
    networks:
      - main
    volumes:
      - "./ocfl/:/etc/share/ocfl"
      - "./config/:/etc/share/config"
      - "./logs/:/etc/share/logs"
    command: npm start /etc/share/config/express.json

  solr:
    image: solr:8.6.3
    environment:
      - SOLR_HEAP=1024m
    ports:
      - "8983:8983"
    expose:
      - "8983"
    networks:
      - main
    volumes:
      - "./solr/:/var/solr/data"
    command: solr-precreate ocfl
    logging:
      driver: none

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    expose:
      - "11211"
    networks:
      - main
