version: '3.1'

networks:
  main:

services:
  oni-express:
    environment:
      - NODE_ENV=development
    build: .
    ports:
      - "8080:8080"
    expose:
      - "80"
    networks:
      - main
    volumes:
      - "./ocfl/:/etc/share/ocfl"
      - "./config/:/etc/share/config"

# Oni-Indexer currently using a build branch matching oni-express
# place it under ../oni-indexer
  oni-indexer:
    #image: image: mikelynch/oni-indexer:v1.0.13
    #image: oni-indexer:latest
    build: ../oni-indexer
    ports:
      - "8090:8090"
    expose:
      - "8090"
    networks:
      - main
    volumes:
      - "./ocfl/:/etc/share/ocfl"
      - "./config/:/etc/share/config"
      - "./logs/:/etc/share/logs"

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    expose:
      - "8983"
    networks:
      - main
    volumes:
      - "./solr/:/var/solr/data"
    command: solr-precreate ocfl
    logging:
        driver: none

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    expose:
      - "11211"
    networks:
      - main
